### ISSUE TITLE
Please enable Two-factor Authentication on your account.

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/internal#10]
Dear all,

@cdnjs/intern @ksprwhite @segphault

Due to security issue, please setup Two-factor Authentication on your GitHub account before 1/18 Mon, if I didn't see you enable it, your cdnjs write permission will be removed temporarily, sorry for the inconvenience caused and thanks for your cooperation.

See:
https://github.com/blog/1614-two-factor-authentication
https://help.github.com/articles/configuring-two-factor-authentication-via-text-message/
https://help.github.com/articles/about-two-factor-authentication/

**Comment by maruilian11** [comment]
done

**Comment by Amomo** [comment]
ok, I have finished it.

**Comment by PeterDaveHello** [comment]
temporarily removed some write permissions, cc @ryankirkman

**Comment by LeaYeh** [comment]
finally...done.

**Comment by PeterDaveHello** [comment]
@LeaYeh I added your permission back.

**Comment by Piicksarn** [comment]
done... :disappointed_relieved:

**Comment by drewfreyling** [comment]
done ages ago.

**Comment by PeterDaveHello** [comment]
@drewfreyling I should tag @segphault, not you, sorry :smile: Just updated.

**Comment by PeterDaveHello** [comment]
Enabled Two-factor Authentication on organization.
