### ISSUE TITLE
add cdnjs domain to HSTS preload list

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/internal#11]

**Comment by PeterDaveHello** [comment]
Submitted, waiting for the result.

**Comment by drewfreyling** [comment]
No word yet?

**Comment by PeterDaveHello** [comment]
https://hstspreload.appspot.com/?domain=cdnjs.com
![screenshot from 2016-08-10 14 29 57](https://cloud.githubusercontent.com/assets/3691490/17543981/f4cb3670-5f06-11e6-9aee-bdedd6769b0b.png)
