### ISSUE TITLE
https issue

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/internal#5]
Let's make it A+? @thomasdavis @ryankirkman 

https://www.ssllabs.com/ssltest/analyze.html?d=cdnjs.com&s=162.159.248.41
`Certificate uses a weak signature. When renewing, ensure you upgrade to SHA2.  MORE INFO »`
![Imgur](http://i.imgur.com/mcWPqFE.png)

**Comment by ryankirkman** [comment]
Great idea!

**Comment by PeterDaveHello** [comment]
I made it few days ago.
https://twitter.com/PeterDaveHello/status/686812391997177856
![temp](https://cloud.githubusercontent.com/assets/3691490/12319992/ea6724f2-bae0-11e5-912d-4f64af931938.png)
